# Generated by Django 5.1.2 on 2024-11-05 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField()),
                ('chest', models.FloatField()),
                ('waist', models.FloatField()),
                ('arm', models.FloatField()),
                ('thigh', models.FloatField()),
                ('fat', models.FloatField()),
                ('calf', models.FloatField()),
                ('hip', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='users.user')),
            ],
        ),
    ]
